# Generated by Django 3.2.3 on 2022-03-17 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('address', models.CharField(blank=True, max_length=150, verbose_name='address')),
                ('city', models.CharField(blank=True, max_length=20, verbose_name='city')),
                ('country', models.CharField(blank=True, max_length=20, verbose_name='country')),
                ('avatar', models.ImageField(blank=True, upload_to='avatar/', verbose_name='avatar')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='username')),
            ],
            options={
                'db_table': 'user_userprofile',
            },
        ),
    ]
